package za.co.wethinkcode.robots.protocol;

import com.google.gson.JsonObject;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import za.co.wethinkcode.robots.direction.Direction;
import za.co.wethinkcode.robots.robot.Robot;
import za.co.wethinkcode.robots.position.Position;
import za.co.wethinkcode.robots.world.World;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * Unit test suite for {@link za.co.wethinkcode.robots.protocol.ProtocolResponse}.
 *
 * This class tests JSON responses generated by the protocol layer,
 * including robot state, error messages, and movement responses.
 * It uses Mockito to simulate robot and position behavior for isolated testing.
 */
public class ProtocolResponseTest {

    Robot robot;
    ProtocolResponse protocol;
    World world;

    @BeforeEach
    void setUp() {
        robot = mock(Robot.class);
        Position position = mock(Position.class);
        world = mock(World.class);

        when(position.getX()).thenReturn(40);
        when(position.getY()).thenReturn(35);
        when(position.toString()).thenReturn("[40,35]");

        when(robot.getPosition()).thenReturn(position);
        when(robot.getOrientation()).thenReturn(Direction.WEST);
        when(robot.getBulletsAvail()).thenReturn(4);
        when(robot.getShieldStrength()).thenReturn(5);
        when(robot.isRepairMode()).thenReturn(false);
        when(robot.isReloadMode()).thenReturn(false);
        when(robot.isAlive()).thenReturn(true);
        when(robot.getName()).thenReturn("Alexis");

        protocol = new ProtocolResponse();
    }

    @Test
    @DisplayName("Test Protocol Robot State Response Structure")
    void testRobotStateResponse() {
        JsonObject response = protocol.getRobotState(robot);

        assertEquals("WEST", response.get("direction").getAsString());
        assertEquals(5, response.get("shields").getAsInt());
        assertEquals(4, response.get("shots").getAsInt());
        assertEquals("NORMAL", response.get("status").getAsString());
        assertEquals("[40,35]", response.get("position").getAsString());

        assertNotNull(response.get("direction"));
        assertTrue(response.has("shields"));
        assertTrue(response.get("position").getAsString().contains("40"));
    }

    @Test
    @DisplayName("Test Location Error Response")
    void testLocationErrorResponse() {
        String response = String.valueOf(protocol.getLocationError());

        assertEquals("{\"result\":\"ERROR\",\"message\":\"Invalid location\"}", response);
        assertTrue(response.contains("ERROR"));
        assertTrue(response.contains("Invalid location"));
        assertTrue(response.contains("result"));
    }

    @Test
    @DisplayName("Test Name Already Taken Error Response")
    void testNameAlreadyTakenError() {
        String response = String.valueOf(protocol.getNameAlreadyTakenError());

        assertEquals("{\"result\":\"ERROR\",\"message\":\"Name already taken\"}", response);
        assertTrue(response.contains("Name already taken"));
        assertTrue(response.contains("result"));
        assertTrue(response.startsWith("{"));
    }

    @Test
    @DisplayName("Test View Response Contains Robot Name")
    void testRobotViewJson() {
        // Update the test to reflect the new code added and how the curriculum describes this protocol
    }

    @Test
    @DisplayName("Test Robot Data JSON Structure")
    void testRobotDataJsonStructure() {
        when(robot.getName()).thenReturn("TestBot");

        JsonObject result = protocol.getRobotData(robot);

        assertTrue(result.has("position"));
        assertTrue(result.has("visibility"));
        assertTrue(result.has("reload"));
        assertTrue(result.has("repair"));
        assertTrue(result.has("shields"));

        assertEquals("[40,35]", result.get("position").getAsString());
    }

    // Iteration 2 Tests
    @Test
    @DisplayName("getMoveResponse returns success message and state")
    void testGetMoveResponse() {
        JsonObject moveJson = protocol.getMoveResponse("Moved 1 step forward", robot);
        assertEquals("OK", moveJson.get("result").getAsString());
        assertEquals("Moved 1 step forward", moveJson.get("message").getAsString());

        JsonObject state = moveJson.getAsJsonObject("state");
        assertEquals("[40,35]", state.get("position").getAsString());
        assertEquals(4, state.get("shots").getAsInt());
        assertEquals(5, state.get("shields").getAsInt());
    }


}