package za.co.wethinkcode.robots.client;

import com.google.gson.JsonObject;
import org.junit.jupiter.api.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test suite for verifying the structure and correctness of the JSON requests
 * generated by the {@link za.co.wethinkcode.robots.client.Request} class.
 *
 * Ensures that commands such as launch, move, turn, and fire are formatted
 * correctly before being sent to the server.
 */
public class RequestTest {
    @Test
    @DisplayName("Launch request")
    void testLaunchRequest() {
        JsonObject obj = Request.launch("Ares", 3, 4);
        assertEquals("Ares", obj.get("robot").getAsString());
        assertEquals("launch", obj.get("command").getAsString());
        assertEquals(3, obj.get("arguments").getAsJsonArray().get(1).getAsInt());
    }

    @Test
    @DisplayName("Forward request")
    void testForwardRequest() {
        JsonObject obj = Request.forward("Posideon", 5);
        assertEquals("Posideon", obj.get("robot").getAsString());
        assertEquals("forward", obj.get("command").getAsString());
        assertEquals(5, obj.get("arguments").getAsJsonArray().get(0).getAsInt());
    }

    @Test
    @DisplayName("Turn right request uses 'right' argument")
    void testTurnRight() {
        JsonObject obj = Request.turnRight("Hermes");
        assertEquals("right", obj.get("arguments").getAsJsonArray().get(0).getAsString());
    }

    @Test
    @DisplayName("Fire request has empty arguments array")
    void testFireRequest() {
        JsonObject obj = Request.fire("Thor");
        assertEquals("fire", obj.get("command").getAsString());
        assertEquals(0, obj.getAsJsonArray("arguments").size());
    }
}
